<?php

/**
 * BaseExcursionCategoryRelations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $excursion_id
 * @property integer $category_id
 * @property Excursion $Excursion
 * @property ExcursionCategory $ExcursionCategory
 * 
 * @method integer                    getExcursionId()       Returns the current record's "excursion_id" value
 * @method integer                    getCategoryId()        Returns the current record's "category_id" value
 * @method Excursion                  getExcursion()         Returns the current record's "Excursion" value
 * @method ExcursionCategory          getExcursionCategory() Returns the current record's "ExcursionCategory" value
 * @method ExcursionCategoryRelations setExcursionId()       Sets the current record's "excursion_id" value
 * @method ExcursionCategoryRelations setCategoryId()        Sets the current record's "category_id" value
 * @method ExcursionCategoryRelations setExcursion()         Sets the current record's "Excursion" value
 * @method ExcursionCategoryRelations setExcursionCategory() Sets the current record's "ExcursionCategory" value
 * 
 * @package    excursia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExcursionCategoryRelations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('excursion_category_relations');
        $this->hasColumn('excursion_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Excursion', array(
             'local' => 'excursion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ExcursionCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}