<?php

/**
 * BaseExcursion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property blob $content
 * @property boolean $is_publish
 * @property integer $city_id
 * @property Doctrine_Collection $ExcursionCategory
 * @property ExcursionCity $ExcursionCity
 * @property Doctrine_Collection $ExcursionCategoryRelations
 * 
 * @method string              getTitle()                      Returns the current record's "title" value
 * @method string              getDescription()                Returns the current record's "description" value
 * @method blob                getContent()                    Returns the current record's "content" value
 * @method boolean             getIsPublish()                  Returns the current record's "is_publish" value
 * @method integer             getCityId()                     Returns the current record's "city_id" value
 * @method Doctrine_Collection getExcursionCategory()          Returns the current record's "ExcursionCategory" collection
 * @method ExcursionCity       getExcursionCity()              Returns the current record's "ExcursionCity" value
 * @method Doctrine_Collection getExcursionCategoryRelations() Returns the current record's "ExcursionCategoryRelations" collection
 * @method Excursion           setTitle()                      Sets the current record's "title" value
 * @method Excursion           setDescription()                Sets the current record's "description" value
 * @method Excursion           setContent()                    Sets the current record's "content" value
 * @method Excursion           setIsPublish()                  Sets the current record's "is_publish" value
 * @method Excursion           setCityId()                     Sets the current record's "city_id" value
 * @method Excursion           setExcursionCategory()          Sets the current record's "ExcursionCategory" collection
 * @method Excursion           setExcursionCity()              Sets the current record's "ExcursionCity" value
 * @method Excursion           setExcursionCategoryRelations() Sets the current record's "ExcursionCategoryRelations" collection
 * 
 * @package    excursia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExcursion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('excursion');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('content', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));
        $this->hasColumn('is_publish', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ExcursionCategory', array(
             'refClass' => 'ExcursionCategoryRelations',
             'local' => 'excursion_id',
             'foreign' => 'category_id'));

        $this->hasOne('ExcursionCity', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ExcursionCategoryRelations', array(
             'local' => 'id',
             'foreign' => 'excursion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}