<?php

/**
 * BaseExcursionCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Excursions
 * 
 * @method string              getTitle()      Returns the current record's "title" value
 * @method Doctrine_Collection getExcursions() Returns the current record's "Excursions" collection
 * @method ExcursionCity       setTitle()      Sets the current record's "title" value
 * @method ExcursionCity       setExcursions() Sets the current record's "Excursions" collection
 * 
 * @package    excursia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExcursionCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('excursion_city');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Excursion as Excursions', array(
             'local' => 'id',
             'foreign' => 'city_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}