<?php

/**
 * BaseExcursionCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Excursions
 * @property Doctrine_Collection $ExcursionCategoryRelations
 * 
 * @method string              getTitle()                      Returns the current record's "title" value
 * @method Doctrine_Collection getExcursions()                 Returns the current record's "Excursions" collection
 * @method Doctrine_Collection getExcursionCategoryRelations() Returns the current record's "ExcursionCategoryRelations" collection
 * @method ExcursionCategory   setTitle()                      Sets the current record's "title" value
 * @method ExcursionCategory   setExcursions()                 Sets the current record's "Excursions" collection
 * @method ExcursionCategory   setExcursionCategoryRelations() Sets the current record's "ExcursionCategoryRelations" collection
 * 
 * @package    excursia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExcursionCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('excursion_category');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Excursion as Excursions', array(
             'refClass' => 'ExcursionCategoryRelations',
             'local' => 'category_id',
             'foreign' => 'excursion_id'));

        $this->hasMany('ExcursionCategoryRelations', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}