<?php

/**
 * ExcursionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ExcursionTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Excursion');
  }
  
  public function getActiveExcursion(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from('Excursion j');
    }
    
    $q->andWhere('j.is_publish = 1');

    return $q->execute();
  }
  
  public function getActiveExcursionCount()
  {
    $q = Doctrine_Query::create()
      ->from('Excursion j')
      ->where('j.is_publish = 1');

    return $q->count();
  }
}