<?php

/**
 * ExcursionCategoryRelationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionCategoryRelationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionCategoryRelationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExcursionCategoryRelations');
    }
}