<?php

/**
 * ExcursionCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    excursia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExcursionCity extends BaseExcursionCity
{
  public function getActiveExcursions($limit)
  {
    $q = Doctrine_Query::create()
      ->from('Excursion j')
      ->where('j.city_id = ?', $this->getId())
      ->limit($limit);

    return Doctrine_Core::getTable('Excursion')->getActiveExcursion($q);
  }
  
  public function getActiveExcursionCount()
  {
    return Doctrine_Core::getTable('Excursion')->getActiveExcursionCount();
  }
}
