generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Excursion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          excursion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   'Экскурсии'
        display: [=title, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
